[functions]
    external_node_modules=["express","ejs","mongoose","lodash"]
    node_bundler="esbuild"
    included_files=["views/*","views/partials/*","public/css/styles.css"]

[[redirects]]
    from = "/*"
    status = 200
    force=true
    to = "/.netlify/functions/api/:splat"
